# Generated by Django 6.0.4 on 2026-04-21 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=255, unique=True)),
                ('active_ingredient', models.CharField(blank=True, max_length=255)),
                ('strength', models.CharField(blank=True, max_length=100)),
                ('dosage_form', models.CharField(blank=True, max_length=100)),
                ('drug_class', models.CharField(blank=True, max_length=160)),
                ('common_side_effects', models.TextField(blank=True)),
                ('serious_warning', models.TextField(blank=True)),
                ('similar_active_ingredients', models.TextField(blank=True)),
                ('similarity_risk_symptoms', models.TextField(blank=True)),
                ('switching_note', models.TextField(blank=True)),
                ('interaction_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['trade_name'],
            },
        ),
        migrations.CreateModel(
            name='MedicationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('dose', models.CharField(max_length=120)),
                ('times', models.JSONField(default=list)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('timezone', models.CharField(default='Africa/Cairo', max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='api.medicine')),
            ],
            options={
                'ordering': ['-is_active', 'start_date', 'medicine_name'],
            },
        ),
        migrations.CreateModel(
            name='ReminderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('taken', 'Taken'), ('missed', 'Missed'), ('skipped', 'Skipped')], default='scheduled', max_length=20)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.medicationreminder')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
