# Generated by Django 6.0.4 on 2026-04-30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def delete_orphan_reminders(apps, schema_editor):
    MedicationReminder = apps.get_model("api", "MedicationReminder")
    MedicationReminder.objects.filter(user__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_medical_record"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(delete_orphan_reminders, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="medicationreminder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
