# Generated by Django 6.0.4 on 2026-05-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reminder_user_non_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='active_ingredient_norm',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='active_ingredient_tokens',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='drug_class_norm',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='search_aliases',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='trade_name_norm',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
